project: 
  type: website

website: 
  navbar: false
  title: "MONSTr"
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/about.qmd
        text: About Us
      - href: content/wikipedia.qmd
        text: On Wikipedia
      - href: content/existingdata.qmd
        text: Uses
      - href: content/papers.qmd
        text: Papers
      - href: content/data.qmd
        text: Data

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]

filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto